# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: echo "This is the $MONGO environment variable"
        env:
          MONGO: ${{ secrets.MONGO }}
      - run: npm run test-ci
        env:
          MONGO: ${{ secrets.MONGO }}
      - run: echo "This is the $SONAR_TOKEN environment variable"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - uses: getsentry/action-git-diff-suggestions@main
        with:
          message: eslint
      - run: npm run lint 
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  test:
    runs-on: ubuntu-latest
    steps:
        - run: npm ci
        - run: npm run build --if-present
        - run: echo "This is the $MONGO environment variable"
          env:
            MONGO: ${{ secrets.MONGO }}
        - run: npm run test-ci
          env:
            MONGO: ${{ secrets.MONGO }}
        - run: echo "This is the $SONAR_TOKEN environment variable"
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        - uses: getsentry/action-git-diff-suggestions@main
          with:
            message: eslint
        - run: npm run lint 
